Vagrant.configure("2") do |config|
  config.vm.define "jenkins-master" do |master|
    master.vm.box = "ubuntu/bionic64"
    master.vm.network "private_network", type: "dhcp"
    master.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get upgrade

    sudo wget -O /usr/share/keyrings/jenkins-keyring.asc \
        https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
      echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc]" \
        https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
        /etc/apt/sources.list.d/jenkins.list > /dev/null

      sudo apt install fontconfig openjdk-17-jre
      java -version

      sudo systemctl enable jenkins
      sudo systemctl start jenkins
      sudo apt-get install -y docker.io
      sudo usermod -aG docker jenkins
      sudo apt-get install -y docker-compose
    SHELL
    master.vm.network "forwarded_port", guest: 8080, host: 8080
  end

  config.vm.define "jenkins-worker" do |worker|
    worker.vm.box = "ubuntu/bionic64"
    worker.vm.network "private_network", type: "dhcp"
    worker.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y openjdk-11-jdk
      sudo apt-get install -y docker.io
    SHELL
  end
end
