---
  - name: Setup Docker and Nginx on EC2 instances
    hosts: ec2_instance
    tasks:
      - name: Update and upgrade apt packages
        apt:
          update_cache: yes
          upgrade: dist
  
      - name: Install Docker
        apt:
          name: docker.io
          state: present
  
      - name: Install Docker Compose
        apt:
          name: docker-compose
          state: present
  
      - name: Create Docker Compose directory
        file:
          path: /opt/docker
          state: directory
  
      - name: Create Docker Compose file for Nginx
        copy:
          dest: /opt/docker/docker-compose.yml
          content: |
            version: '3'
            services:
              nginx:
                image: nginx
                ports:
                  - "80:80"
  
      - name: Pull Nginx Docker image
        docker_image:
          name: nginx
          source: pull
  
      - name: Run Nginx with Docker Compose
        command: docker-compose up -d
        args:
          chdir: /opt/docker
  