- name: Set up Jenkins master
  hosts: jenkins_master
  become: yes
  tasks:
    - name: Install Java
      yum:
        name: java-1.8.0-openjdk
        state: present

    - name: Add Jenkins repo
      yum_repository:
        name: Jenkins
        description: Jenkins-stable
        baseurl: http://pkg.jenkins.io/redhat-stable/
        gpgcheck: no

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Start Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes

    - name: Install nginx
      yum:
        name: nginx
        state: present

    - name: Configure nginx as a reverse proxy
      copy:
        content: |
          server {
              listen       80;
              server_name  localhost;

              location / {
                  proxy_pass         http://localhost:8080;
                  proxy_set_header   Host $host;
              }
          }
        dest: /etc/nginx/conf.d/jenkins.conf

    - name: Start nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes
